### ISSUE TITLE
Can't run. Error at module.js:328

### ISSUE THREAD

**Issue by timkinnane** [dowjones/generator-slack-slash#1]
Can't run the generator. Installed globally, updated brew, npm, reinstalled yeoman. No luck.
Looks like this repo is out of date, possibly incompatible with current version of node or yo?

```
$ yo slack-slash
module.js:328
    throw err;
    ^

Error: Cannot find module '../../helpers'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-slack-slash/generators/app/index.js:6:15)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
```

**Comment by adamgruber** [comment]
This was an error caused by a bad `package.json` file. I just published 1.0.1 to fix it so things should run smoothly now once you grab the latest version. Let me know if they don't.
